name: Package Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 3"

permissions:
  contents: read
  packages: write

jobs:
  package-cleanup:
    name: Cleanup Old GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged package versions
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: GameServerManagers
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: gameserver
          tag-selection: untagged
          keep-n-most-recent: 1
          cut-off: 1s
          dry-run: true

  package-cleanup-2:
    name: Cleanup Old GitHub Packages 2
    needs: package-cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged package versions
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: GameServerManagers
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: gameserver
          tag-selection: untagged
          keep-n-most-recent: 1
          cut-off: 1s
          dry-run: true

  package-cleanup-3:
    name: Cleanup Old GitHub Packages 3
    needs: package-cleanup-2
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged package versions
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: GameServerManagers
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: gameserver
          tag-selection: untagged
          keep-n-most-recent: 1
          cut-off: 1s
          dry-run: true
