name: Package Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 3"

jobs:
  package-cleanup:
    name: Cleanup Old GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: gameserver
          package-type: container
          min-versions-to-keep: 1
          delete-only-untagged-versions: true

  package-cleanup-2:
    name: Cleanup Old GitHub Packages 2
    needs: package-cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: gameserver
          package-type: container
          min-versions-to-keep: 1
          delete-only-untagged-versions: true

  package-cleanup-3:
    name: Cleanup Old GitHub Packages 3
    needs: package-cleanup-2
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: gameserver
          package-type: container
          min-versions-to-keep: 1
          delete-only-untagged-versions: true
