name: Package Cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 3"

permissions:
  contents: read
  packages: write

jobs:
  package-cleanup:
    name: Cleanup Old GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged package versions
        uses: snok/container-retention-policy@v3.1.0
        with:
          account: GameServerManagers
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: gameserver
          tag-selection: untagged
          keep-n-most-recent: 1
          cut-off: 1s
          dry-run: true
